# Generated by Django 3.1.1 on 2020-09-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receuil',
        ),
    ]
