# Generated by Django 3.1.1 on 2020-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_receuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='arret',
            name='annee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
