# Generated by Django 3.1.1 on 2020-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_arret_num_receuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=30)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
