# Generated by Django 3.1.1 on 2020-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200909_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='arret',
            name='Armes_juridictionnelles',
            field=models.TextField(default=''),
        ),
    ]
